### ISSUE TITLE
Make raspberry pi shut down when bombermaan is closed

### ISSUE THREAD

**Issue by eaglewyng** [lukehsiao/BYU_Bomberman#6]

**Comment by lukehsiao** [comment]
You finished this? How did you do it?

**Comment by eaglewyng** [comment]
I added a scripts folder to the github project with a script that checks if the bombermaaan process is running, and then added a root crontab job to the raspberry pi that runs the script every minute. If the bombermaaan process isn't running, then it shuts the computer down using "shutdown -h now". I added some directions in the readme right before the instructions for the manual shutdown that describe how to do this.

**Comment by lukehsiao** [comment]
Sweet awesome.
