### ISSUE TITLE
Make new BYU Bomberman Level

### ISSUE THREAD

**Issue by eaglewyng** [lukehsiao/BYU_Bomberman#7]

**Comment by lukehsiao** [comment]
One more thought on this. It might be nice to eliminate the other levels. One of the controllers is hooked up to the arrow keys, which means that if a student is just mashing buttons while the demo leader is trying to navigate menus, the student might mess with the navigation. It might be nice just to have a single BYU level, and the demo leader just has to hit enter and won't have to worry about the students messing with it.

**Comment by eaglewyng** [comment]
Added the new level, and removed the other levels from the levels folder.

**Comment by lukehsiao** [comment]
Sweet awesome.
